# Generated by Django 3.1.6 on 2021-06-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
    ]
